blog_index:
    path:     /
    defaults: { _controller: MyBlogBundle:Default:index }

blog_new:
    path: /new
    defaults: { _controller: MyBlogBundle:Default:new }

blog_show:
    path: /{id}/show
    defaults: { _controller: MyBlogBundle:Default:show }
    requirements:
        id: \d+

blog_delete:
    path:  /{id}/delete
    defaults: { _controller: MyBlogBundle:Default:delete }
    requirements:
        id: \d+

blog_edit:
    path:  /{id}/edit
    defaults: { _controller: MyBlogBundle:Default:edit }
    requirements:
        id: \d+
